# Generated by Django 4.1.1 on 2023-04-04 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0001_initial'),
        ('common', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('provider_order_id', models.CharField(default='', max_length=40)),
                ('payment_id', models.CharField(default='', max_length=36)),
                ('signature_id', models.CharField(default='', max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_type', models.CharField(default='', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.orders')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbook.productsss')),
            ],
            options={
                'db_table': 'order_dt',
            },
        ),
    ]
