# Generated by Django 4.1.1 on 2023-03-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('adbook', '0007_remove_product_author'),
        ('customer', '0002_carts_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbook.productsss')),
            ],
        ),
    ]
