# Generated by Django 4.1.1 on 2023-03-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0008_remove_productss_author_remove_productss_seller_and_more'),
        ('customer', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbook.products'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbook.products'),
        ),
    ]
