# Generated by Django 4.1.1 on 2023-02-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('adbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=100)),
                ('product_number', models.BigIntegerField()),
                ('language', models.CharField(default='', max_length=50)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='product/')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adbook.author')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
