# Generated by Django 4.1.1 on 2023-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='author/')),
            ],
        ),
        migrations.CreateModel(
            name='Bulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='bulk/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
