# Generated by Django 4.1.1 on 2023-03-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0003_alter_order_product'),
        ('adbook', '0005_delete_bulk_remove_product_author_name_and_more'),
    ]

    operations = [
    ]
