# Generated by Django 4.1.1 on 2023-03-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0006_merge_20230303_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
