# Generated by Django 4.1.1 on 2023-03-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0007_remove_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productss',
            name='author',
        ),
        migrations.RemoveField(
            model_name='productss',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='productsss',
            name='author',
        ),
        migrations.RemoveField(
            model_name='productsss',
            name='seller',
        ),
        migrations.AlterField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adbook.products'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Productss',
        ),
    ]
