# Generated by Django 4.1.1 on 2023-03-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbook', '0008_remove_productss_author_remove_productss_seller_and_more'),
        ('customer', '0004_alter_carts_product_alter_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productsss',
        ),
    ]
